### ISSUE TITLE
The canonical "Mnemonic::generate_in_with" example fails to meet bounds

### ISSUE THREAD

**Issue by mplsgrant** [rust-bitcoin/rust-bip39#21]
The [canonical implementation](https://github.com/rust-bitcoin/rust-bip39/blob/520e15a6e5b86940dae2d386d90b4b3616491d13/src/lib.rs#L230
) of `Mnemonic::generate_in_with` generates the following errors:
    
    the trait `rand_core::RngCore` is not implemented for `ThreadRng`
    the trait `rand_core::RngCore` is not implemented for `ThreadRng`

**Comment by tcharding** [comment]
Can you elaborate please, I am unable to reproduce. I tried
- Running `cargo test` to run the rustdoc tests you link to, passes for me locally
- Creating a stand alone crate with
```
use bip39::{Mnemonic, Language};

fn main() {
    let mut rng = rand::thread_rng();
    let _ = Mnemonic::generate_in_with(&mut rng, Language::English, 24).unwrap();
}
```
And tried using `rust-bip39` dependency v1.0.1 and also the tip of master.

**Comment by mplsgrant** [comment]
Thanks for having a look!

I went ahead and created a repo: https://github.com/mplsgrant/mnemonic-generate/

When I run `cargo run` I get the same errors.

**Comment by tcharding** [comment]
Oh its because of the `rand` version. The `rust-bitcoin` stack is on rand v0.6 for reasons I can't remember right at this second but it will be getting bumped along with the soon (TM) to be bumped MSRV. Changing the `rand` dependency in the linked crate to `0.6` removes the build error.

More technically, and I could be wrong here, the error message is because there are two versions of `rand_core` being used as dependencies and the `ThreadRng` you are getting is the v0.8.5 one not the one that implements the required trait (which is from v0.6).

Hope this helps.

**Comment by mplsgrant** [comment]
Changing rand's version to 0.6 worked for me. Thank you!
